### ISSUE TITLE
Wrapper is not available for PHP 7

### ISSUE THREAD

**Issue by reuhtte** [bitsoex/bitso-php#1]
When I tried to install the wrapper I got this error:
```
$composer require "bitso/bitso-php:*"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

Problem 1
    - Installation request for bitso/bitso-php * -> satisfiable by bitso/bitso-php[dev-master].
    - bitso/bitso-php dev-master requires php ^5.0 -> your PHP version (7.0.18) does not satisfy that requirement.
```
Are you going to support PHP 7 any time soon?

Thanks.

**Comment by julyanserra** [comment]
Hi @reuhtte ,
I have fixed some minor syntax files in the package composer file and you should now be able to use this wrapper with your version of PHP with no problem. Please reply on this thread if you can successfully install the Wrapper or if you have other issues.

All the best!

**Comment by reuhtte** [comment]
It's working now. Thanks!
