### ISSUE TITLE
Error when trying to cancel order: "Undefined variable: params"

### ISSUE THREAD

**Issue by fdbatista** [bitsoex/bitso-php#5]
Hello, team.

I am getting this error when trying to cancel an active order: `"Undefined variable: params"`

I am following the example in the README file, like this:

```php
$response = $this->bitsoAPI->cancel_order(['rsYbXsOQn3xn7Mkr']);
```

If I pass `all` as parameter everything works fine. But it does not when passing a single oid.

This is the source code for the `cancel_order` method from the `bitso` class:

```php
function cancel_order($ids){
  	/*
    Cancels an open order
    Args:
      order_id (str):
        A Bitso Order ID.
        
    Returns:
      A list of Order IDs (OIDs) for the canceled orders. Orders may not be successfully cancelled if they have been filled, have been already cancelled, or the OIDs are incorrect
    */
    if ($ids === 'all') {
	$parameters = 'all';
    } else {
	$parameters = implode('', $params);
    }

    $path = $this->url . "/orders/".$parameters;
    $RequestPath = "/api/v3/orders/".$parameters;
    $nonce = $this->makeNonce();
    $HTTPMethod = 'DELETE';
    $JSONPayload = '';
    $type = 'PRIVATE';

    return $this->getData($nonce,$path,$RequestPath,$HTTPMethod,$JSONPayload,$type);
  }
```

As you can see, no variable named `params` is defined when the method tries to execute `implode('', $params);`.

What's wrong here?

**Comment by fdbatista** [comment]
If I manually replace `$parameters = implode('', $params);` with `$parameters = implode('', $ids);` the method works.
Is this a typo in the code base? It looks like.

Please, can @domix or someone else from the team take a look at this? Maybe I should create a MR...

**Comment by julyanserra** [comment]
Hi @fdbatista, it does seem like this is a bug. And your solution is the correct one if you'd like to create a Pull Request with the change you mention it would be fantastic!

**Comment by fdbatista** [comment]
Great, I will do that. Right now I don't need the functionality this method provides, but I will need it in the future.
It's weird that no other user had this issue before...

**Comment by fdbatista** [comment]
> Hi @fdbatista, it does seem like this is a bug. And your solution is the correct one if you'd like to create a Pull Request with the change you mention it would be fantastic!

Hi, @julyanserra. I've created the PR: #7
Have a good day!
